---
#
# Ansible managed
#
repository:
  description: Install and configure zabbix_server on your system.
  homepage: https://robertdebock.nl/
  topics: zabbix, server, monitoring, ansible, molecule, playbook
